version: '2.1'

volumes:
  cassandra_data:
    driver: local

services:
  cassandra:
    # image: 'docker.io/bitnami/cassandra:3-debian-10'
    container_name: cassandra_db
    build: services/.
    ports:
      - '7000:7000'
      - '9042:9042'
    volumes:
      - 'cassandra_data:/bitnami'
    environment:
      - CASSANDRA_SEEDS=cassandra
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_PASSWORD=cassandra

